$ lmstrix test --all
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/lmstrix", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/__main__.py", line 166, in main
    fire.Fire(LMStrixCLI)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/__main__.py", line 61, in test
    self.service.test_models(
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/api/main.py", line 455, in test_models
    models_to_test = _get_models_to_test(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/api/main.py", line 64, in _get_models_to_test
    if tester._is_embedding_model(m):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ContextTester' object has no attribute '_is_embedding_model'
Othello:adam adam$


Othello:adam adam$ lmstrix test --all
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/lmstrix", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/__main__.py", line 166, in main
    fire.Fire(LMStrixCLI)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/__main__.py", line 61, in test
    self.service.test_models(
  File "/Users/Shared/lmstudio/lmstrix/src/lmstrix/api/main.py", line 479, in test_models
    models_to_test = tester._filter_models_for_testing(models_to_test)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ContextTester' object has no attribute '_filter_models_for_testing'
Othello:adam adam$

